# Generated by Django 3.2.9 on 2022-01-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='expirydate',
        ),
    ]
