# Generated by Django 3.2.9 on 2022-01-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_item_expirydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='expirydate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
